begin;

update public.plans
set
  exibir_na_pagina_planos = false,
  destaque = false,
  updated_at = now()
where exibir_na_pagina_planos = true
  and id not in (
    'f6c55498-7b22-4ac2-9703-bf2bdd0cc431',
    'c7a0cbe2-c7b8-4f18-b6d2-aad40d95bb65',
    '2b2510b4-cb58-4dd4-ab83-f6b4fdf2fe1f',
    'd0cb4b21-f795-4b2f-bb8c-fb5be5118f6e'
  );

insert into public.plans (
  id,
  nome,
  descricao,
  valor,
  valor_original,
  periodicidade,
  tipo,
  badge,
  cta_texto,
  destaque,
  ordem,
  limite_conversas,
  exibir_na_pagina_planos,
  limite_agentes,
  caracteristicas,
  ativo,
  valor_primeira_cobranca,
  codigo_personalizado,
  is_personalizado,
  frequencia_dias,
  trial_dias,
  created_at,
  updated_at
)
values
(
  'f6c55498-7b22-4ac2-9703-bf2bdd0cc431',
  'IA Ilimitada',
  'Todas as ferramentas da plataforma em uma estrutura enxuta para quem quer operar com IA ilimitada desde o início.',
  49.99,
  null,
  'mensal',
  'padrao',
  'Entrada completa',
  'Começar no ilimitado',
  false,
  1,
  -1,
  true,
  1,
  '[
    "Todas as ferramentas principais da plataforma",
    "IA atendendo 24/7 com respostas ilimitadas",
    "1 operação principal conectada",
    "CRM, fluxos e automações inclusos",
    "Suporte via WhatsApp",
    "Estrutura ideal para começar sem travas"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  'c7a0cbe2-c7b8-4f18-b6d2-aad40d95bb65',
  'IA Ilimitada Pro',
  'Todas as ferramentas com mais estrutura, números adicionais ilimitados, atualizações automáticas completas e prioridade maior nas respostas da IA.',
  99.00,
  null,
  'mensal',
  'padrao',
  'Mais estrutura',
  'Ir para o plano completo',
  false,
  2,
  -1,
  true,
  -1,
  '[
    "Todas as ferramentas principais da plataforma",
    "Números adicionais ilimitados",
    "Atualizações automáticas completas",
    "Prioridade maior nas respostas da IA",
    "Mais estrutura para operações simultâneas",
    "Suporte prioritário via WhatsApp"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  '2b2510b4-cb58-4dd4-ab83-f6b4fdf2fe1f',
  'Plano Configurado por Especialista',
  'Tudo configurado por especialista, com implantação guiada para colocar a operação no ar com mais velocidade e menos atrito.',
  199.00,
  null,
  'mensal',
  'padrao',
  'Especialista',
  'Quero o especialista',
  false,
  3,
  -1,
  true,
  -1,
  '[
    "Tudo do plano de R$ 99",
    "Configuração completa feita por especialista",
    "Ajustes iniciais guiados para o seu cenário",
    "Implantação assistida para acelerar a operação",
    "Menos trabalho manual no começo",
    "Prioridade alta no acompanhamento"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  'd0cb4b21-f795-4b2f-bb8c-fb5be5118f6e',
  'IA Dedicada',
  'Operação premium com IA dedicada para alto volume de respostas, implantação assistida e foco em escala contínua.',
  299.99,
  null,
  'mensal',
  'padrao',
  'IA dedicada',
  'Quero IA dedicada',
  true,
  4,
  -1,
  true,
  -1,
  '[
    "Tudo do plano com especialista",
    "IA dedicada para grande volume de respostas",
    "Estrutura pensada para operações intensas",
    "Implantação assistida com foco em escala",
    "Prioridade máxima no suporte",
    "Operação pronta para crescer com menos fila"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
)
on conflict (id) do update
set
  nome = excluded.nome,
  descricao = excluded.descricao,
  valor = excluded.valor,
  valor_original = excluded.valor_original,
  periodicidade = excluded.periodicidade,
  tipo = excluded.tipo,
  badge = excluded.badge,
  cta_texto = excluded.cta_texto,
  destaque = excluded.destaque,
  ordem = excluded.ordem,
  limite_conversas = excluded.limite_conversas,
  exibir_na_pagina_planos = excluded.exibir_na_pagina_planos,
  limite_agentes = excluded.limite_agentes,
  caracteristicas = excluded.caracteristicas,
  ativo = excluded.ativo,
  valor_primeira_cobranca = excluded.valor_primeira_cobranca,
  codigo_personalizado = excluded.codigo_personalizado,
  is_personalizado = excluded.is_personalizado,
  frequencia_dias = excluded.frequencia_dias,
  trial_dias = excluded.trial_dias,
  updated_at = now();

commit;
