begin;

update public.plans
set
  exibir_na_pagina_planos = false,
  destaque = false,
  updated_at = now()
where exibir_na_pagina_planos = true
  and id not in (
    'f6c55498-7b22-4ac2-9703-bf2bdd0cc431',
    'c7a0cbe2-c7b8-4f18-b6d2-aad40d95bb65',
    '2b2510b4-cb58-4dd4-ab83-f6b4fdf2fe1f',
    'd0cb4b21-f795-4b2f-bb8c-fb5be5118f6e',
    '83c7ee7f-97b0-45bd-9b97-4f53af78f814'
  );

insert into public.plans (
  id,
  nome,
  descricao,
  valor,
  valor_original,
  periodicidade,
  tipo,
  badge,
  cta_texto,
  destaque,
  ordem,
  limite_conversas,
  exibir_na_pagina_planos,
  limite_agentes,
  caracteristicas,
  ativo,
  valor_primeira_cobranca,
  codigo_personalizado,
  is_personalizado,
  frequencia_dias,
  trial_dias,
  created_at,
  updated_at
)
values
(
  'f6c55498-7b22-4ac2-9703-bf2bdd0cc431',
  'IA Ilimitada',
  'Todas as ferramentas da plataforma em uma estrutura enxuta para entrar com IA ilimitada e manter a operacao ativa desde o primeiro dia.',
  49.99,
  null,
  'mensal',
  'padrao',
  'Entrada completa',
  'Comecar agora',
  false,
  1,
  -1,
  true,
  1,
  '[
    "Todas as ferramentas principais da plataforma",
    "IA ilimitada atendendo 24/7",
    "1 operacao principal conectada",
    "CRM, fluxos e automacoes inclusos",
    "Suporte via WhatsApp",
    "Estrutura enxuta para comecar sem travar crescimento"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  'c7a0cbe2-c7b8-4f18-b6d2-aad40d95bb65',
  'IA Ilimitada Pro',
  'Todas as ferramentas com mais estrutura, numeros adicionais ilimitados, atualizacoes automaticas completas e prioridade maior nas respostas da IA.',
  99.00,
  null,
  'mensal',
  'padrao',
  'Mais estrutura',
  'Subir para o Pro',
  false,
  2,
  -1,
  true,
  -1,
  '[
    "Tudo do plano de R$ 49,99",
    "Numeros adicionais ilimitados",
    "Atualizacoes automaticas completas do sistema",
    "Respostas da IA com prioridade maior",
    "Mais estrutura para operacoes simultaneas",
    "Suporte prioritario via WhatsApp"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  '2b2510b4-cb58-4dd4-ab83-f6b4fdf2fe1f',
  'Plano Configurado por Especialista',
  'Sua IA fica configurada por especialista, com setup guiado e entrada operacional em ate 3 dias uteis para voce operar mais rapido.',
  199.00,
  null,
  'mensal',
  'padrao',
  'Ate 3 dias uteis',
  'Quero configuracao rapida',
  false,
  3,
  -1,
  true,
  -1,
  '[
    "Tudo do plano de R$ 99",
    "Configuracao completa da IA feita por especialista",
    "Entrega operacional em ate 3 dias uteis apos confirmacao",
    "Ajustes iniciais guiados para o seu cenario",
    "Menos trabalho manual no comeco",
    "Prioridade alta no acompanhamento de implantacao"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  'd0cb4b21-f795-4b2f-bb8c-fb5be5118f6e',
  'IA Dedicada',
  'Operacao premium com IA dedicada para alto volume de respostas, implantacao assistida e foco em escala continua.',
  299.99,
  null,
  'mensal',
  'padrao',
  'IA dedicada',
  'Quero IA dedicada',
  false,
  4,
  -1,
  true,
  -1,
  '[
    "Tudo do plano de R$ 199",
    "IA dedicada para alto volume de respostas",
    "Estrutura pensada para operacoes intensas",
    "Implantacao assistida com foco em escala continua",
    "Prioridade maxima na fila operacional",
    "Operacao pronta para crescer com menos fila"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
),
(
  '83c7ee7f-97b0-45bd-9b97-4f53af78f814',
  'IA com Consultor',
  'Plano premium com IA e consultor dedicado na conta ao longo do dia, configuracao rapida e acompanhamento continuo da operacao.',
  497.99,
  null,
  'mensal',
  'padrao',
  'Consultor na conta',
  'Quero o consultor',
  true,
  5,
  -1,
  true,
  -1,
  '[
    "Tudo do plano de R$ 299,99",
    "Consultor dedicado na conta ao longo do dia",
    "Configuracao rapida com ajustes continuos",
    "Atendimento para urgencias e refinamentos da operacao",
    "Acompanhamento proximo de segunda a sexta",
    "Camada premium para quem quer a conta sempre assistida"
  ]'::jsonb,
  true,
  null,
  null,
  false,
  30,
  0,
  now(),
  now()
)
on conflict (id) do update
set
  nome = excluded.nome,
  descricao = excluded.descricao,
  valor = excluded.valor,
  valor_original = excluded.valor_original,
  periodicidade = excluded.periodicidade,
  tipo = excluded.tipo,
  badge = excluded.badge,
  cta_texto = excluded.cta_texto,
  destaque = excluded.destaque,
  ordem = excluded.ordem,
  limite_conversas = excluded.limite_conversas,
  exibir_na_pagina_planos = excluded.exibir_na_pagina_planos,
  limite_agentes = excluded.limite_agentes,
  caracteristicas = excluded.caracteristicas,
  ativo = excluded.ativo,
  valor_primeira_cobranca = excluded.valor_primeira_cobranca,
  codigo_personalizado = excluded.codigo_personalizado,
  is_personalizado = excluded.is_personalizado,
  frequencia_dias = excluded.frequencia_dias,
  trial_dias = excluded.trial_dias,
  updated_at = now();

commit;
