CREATE TABLE IF NOT EXISTS provider_config (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  is_active boolean DEFAULT false,
  send_to_ai boolean DEFAULT true,
  salon_name varchar(255),
  salon_type varchar(50) DEFAULT 'provider',
  phone varchar(50),
  address varchar(500),
  opening_hours jsonb DEFAULT '{}'::jsonb,
  slot_duration integer DEFAULT 30,
  buffer_between integer DEFAULT 10,
  max_advance_days integer DEFAULT 30,
  min_notice_hours integer DEFAULT 2,
  min_notice_minutes integer DEFAULT 0,
  allow_cancellation boolean DEFAULT true,
  cancellation_notice_hours integer DEFAULT 4,
  use_services boolean DEFAULT true,
  use_professionals boolean DEFAULT true,
  allow_multiple_services boolean DEFAULT false,
  service_name varchar(255),
  welcome_message text,
  booking_confirmation_message text,
  reminder_message text,
  cancellation_message text,
  closed_message text,
  humanize_responses boolean DEFAULT true,
  use_customer_name boolean DEFAULT true,
  response_variation boolean DEFAULT true,
  response_delay_min integer DEFAULT 1000,
  response_delay_max integer DEFAULT 3000,
  ai_instructions text,
  display_instructions text,
  google_calendar_enabled boolean DEFAULT false,
  google_calendar_id varchar(255),
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinic_config (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  is_active boolean DEFAULT false,
  send_to_ai boolean DEFAULT true,
  salon_name varchar(255),
  salon_type varchar(50) DEFAULT 'clinic',
  phone varchar(50),
  address varchar(500),
  opening_hours jsonb DEFAULT '{}'::jsonb,
  slot_duration integer DEFAULT 30,
  buffer_between integer DEFAULT 10,
  max_advance_days integer DEFAULT 30,
  min_notice_hours integer DEFAULT 2,
  min_notice_minutes integer DEFAULT 0,
  allow_cancellation boolean DEFAULT true,
  cancellation_notice_hours integer DEFAULT 4,
  use_services boolean DEFAULT true,
  use_professionals boolean DEFAULT true,
  allow_multiple_services boolean DEFAULT false,
  service_name varchar(255),
  welcome_message text,
  booking_confirmation_message text,
  reminder_message text,
  cancellation_message text,
  closed_message text,
  humanize_responses boolean DEFAULT true,
  use_customer_name boolean DEFAULT true,
  response_variation boolean DEFAULT true,
  response_delay_min integer DEFAULT 1000,
  response_delay_max integer DEFAULT 3000,
  ai_instructions text,
  display_instructions text,
  google_calendar_enabled boolean DEFAULT false,
  google_calendar_id varchar(255),
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS provider_services (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  description text,
  duration_minutes integer DEFAULT 30,
  price numeric(10,2),
  is_active boolean DEFAULT true,
  color varchar(50),
  display_order integer DEFAULT 0,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinic_services (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  description text,
  duration_minutes integer DEFAULT 30,
  price numeric(10,2),
  is_active boolean DEFAULT true,
  color varchar(50),
  display_order integer DEFAULT 0,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS provider_professionals (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  bio text,
  avatar_url text,
  is_active boolean DEFAULT true,
  work_schedule jsonb DEFAULT '{}'::jsonb,
  display_order integer DEFAULT 0,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinic_professionals (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name varchar(255) NOT NULL,
  bio text,
  avatar_url text,
  is_active boolean DEFAULT true,
  work_schedule jsonb DEFAULT '{}'::jsonb,
  display_order integer DEFAULT 0,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS provider_appointments (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id varchar,
  client_name varchar(255) NOT NULL,
  client_phone varchar(50) NOT NULL,
  client_email varchar(255),
  service_name varchar(255),
  appointment_date varchar(20) NOT NULL,
  start_time varchar(10) NOT NULL,
  end_time varchar(10) NOT NULL,
  duration_minutes integer DEFAULT 60,
  service_id varchar REFERENCES provider_services(id) ON DELETE SET NULL,
  professional_id varchar REFERENCES provider_professionals(id) ON DELETE SET NULL,
  professional_name varchar(255),
  location varchar(500),
  location_type varchar(50) DEFAULT 'presencial',
  meeting_link varchar(500),
  status varchar(50) DEFAULT 'pending',
  confirmed_by_client boolean DEFAULT false,
  confirmed_by_business boolean DEFAULT false,
  confirmed_at timestamp,
  cancelled_at timestamp,
  cancelled_by varchar(50),
  cancellation_reason text,
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp,
  reminder_times_sent jsonb DEFAULT '[]'::jsonb,
  google_event_id varchar(255),
  google_calendar_synced boolean DEFAULT false,
  client_notes text,
  internal_notes text,
  custom_message text,
  use_custom_message boolean DEFAULT false,
  custom_message_sent_at timestamp,
  created_by_ai boolean DEFAULT false,
  ai_confirmation_pending boolean DEFAULT false,
  ai_conversation_context jsonb,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinic_appointments (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  conversation_id varchar,
  client_name varchar(255) NOT NULL,
  client_phone varchar(50) NOT NULL,
  client_email varchar(255),
  service_name varchar(255),
  appointment_date varchar(20) NOT NULL,
  start_time varchar(10) NOT NULL,
  end_time varchar(10) NOT NULL,
  duration_minutes integer DEFAULT 60,
  service_id varchar REFERENCES clinic_services(id) ON DELETE SET NULL,
  professional_id varchar REFERENCES clinic_professionals(id) ON DELETE SET NULL,
  professional_name varchar(255),
  location varchar(500),
  location_type varchar(50) DEFAULT 'presencial',
  meeting_link varchar(500),
  status varchar(50) DEFAULT 'pending',
  confirmed_by_client boolean DEFAULT false,
  confirmed_by_business boolean DEFAULT false,
  confirmed_at timestamp,
  cancelled_at timestamp,
  cancelled_by varchar(50),
  cancellation_reason text,
  reminder_sent boolean DEFAULT false,
  reminder_sent_at timestamp,
  reminder_times_sent jsonb DEFAULT '[]'::jsonb,
  google_event_id varchar(255),
  google_calendar_synced boolean DEFAULT false,
  client_notes text,
  internal_notes text,
  custom_message text,
  use_custom_message boolean DEFAULT false,
  custom_message_sent_at timestamp,
  created_by_ai boolean DEFAULT false,
  ai_confirmation_pending boolean DEFAULT false,
  ai_conversation_context jsonb,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS provider_google_calendar_tokens (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  access_token text,
  refresh_token text,
  token_type varchar(50),
  expiry_date timestamp,
  scope text,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clinic_google_calendar_tokens (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  access_token text,
  refresh_token text,
  token_type varchar(50),
  expiry_date timestamp,
  scope text,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_provider_services_user ON provider_services(user_id);
CREATE INDEX IF NOT EXISTS idx_clinic_services_user ON clinic_services(user_id);
CREATE INDEX IF NOT EXISTS idx_provider_professionals_user ON provider_professionals(user_id);
CREATE INDEX IF NOT EXISTS idx_clinic_professionals_user ON clinic_professionals(user_id);
CREATE INDEX IF NOT EXISTS idx_provider_appointments_user_date ON provider_appointments(user_id, appointment_date);
CREATE INDEX IF NOT EXISTS idx_clinic_appointments_user_date ON clinic_appointments(user_id, appointment_date);
